dpi = 300
inner_margin = 1
resize = false
double_sided = true  # write text on both sides

[page]
height = 297
width = 210

[badge]
height = 147
width = 104

[name]
height = 24.5
width = 93.6
vertical_offset = 66
font_name = "DejaVuSans.ttf"
font_size = 256
color = "0x000000"

[lastname]
height = 21
width = 93.6
vertical_offset = 88
font_name = "DejaVuSans.ttf"
font_size = 172
color = "0x000000"

[group]
height = 18
width = 93.6
vertical_offset = 105
# TODO: add a logic that if there is no last name the vertical offset of group is a bit higher
font_name = "DejaVuSans.ttf"
font_size = 136
color = "0x000000"
